-- 与 chuanzhiback/uploads 目录下实际资源命名对齐，写入 ar_project（便于库内查询与后续改读库）
-- 使用 ON DUPLICATE KEY UPDATE，重复启动时刷新路径与文案

USE your_database_name; -- Replace 'your_database_name' with the actual name of your database

INSERT INTO ar_project (id, name, description, detail, instruction,
                        cover_image, marker_image, video_url, duration, category, is_hot,
                        create_time, update_time)
VALUES (1,
        '景德镇青花瓷 AR 体验',
        '对准青花瓷主题画面，叠加展示纹样与烧制工艺讲解视频。',
        '识别景德镇青花瓷相关画面后，在实景上叠加短视频，介绍釉色、纹样与烧制工序。',
        '1. 开启相机权限\n2. 对准青花瓷海报或展品图\n3. 稳定握持手机等待画面叠加\n4. 可重复观看讲解',
        '/uploads/heritage_index/recommend_heritage_jingdezhenciqi.jpg',
        '/uploads/photo_ARExperinece/deomphoto.jpg',
        '/uploads/video_ARExperinece/景德镇青花瓷.mp4',
        '约 2 分钟',
        '陶瓷艺术',
        1,
        NOW(6), NOW(6)),
       (2,
        '苏绣·双面绣 AR 体验',
        '对准绣品图片，叠加展示绣线走向与细节放大视频。',
        '对准苏绣主题图片，播放绣线铺陈、纹理放大与工艺讲解短视频。',
        '1. 开启相机权限\n2. 对准苏绣海报或绣品图\n3. 保持稳定等待视频叠加\n4. 观察针法与线迹',
        '/uploads/masters_InheritorCommunit/master_suxiu.jpg',
        '/uploads/masters_InheritorCommunit/master_suxiu.jpg',
        '/uploads/video_ARExperinece/苏绣双面绣AR体验视频.mp4',
        '约 2 分钟',
        '传统技艺',
        1,
        NOW(6), NOW(6)),
       (3,
        '青铜器纹样 AR 体验',
        '识别青铜器纹饰图，播放纹样解析与场景还原类视频。',
        '对准青铜器纹饰图片，视频展示纹样含义与复原示意。',
        '1. 保持光线充足\n2. 对准纹饰清晰图片\n3. 稳定设备等待叠加\n4. 跟随讲解了解寓意',
        '/uploads/ar_index/ar_bronze1.jpg',
        '/uploads/ar_index/ar_bronze2.jpg',
        '/uploads/video_ARExperinece/青铜器纹样AR体验视频.mp4',
        '约 2 分钟',
        '青铜艺术',
        0,
        NOW(6), NOW(6)),
       (4,
        '少林武术 AR 体验',
        '对准武术主题海报，叠加身法与招式演示短片。',
        '识别武术类图片后，叠加演示短片并配合简要讲解。',
        '1. 注意周围环境安全\n2. 对准武术海报\n3. 稳定握持设备\n4. 可多次重播',
        '/uploads/heritage_index/recommend_heritage_wushu.jpg',
        '/uploads/photo_ARExperience.png',
        '/uploads/video_ARExperinece/少林武术AR体验视频生成.mp4',
        '约 90 秒',
        '武术',
        0,
        NOW(6), NOW(6))
ON DUPLICATE KEY UPDATE name         = VALUES(name),
                        description  = VALUES(description),
                        detail       = VALUES(detail),
                        instruction  = VALUES(instruction),
                        cover_image  = VALUES(cover_image),
                        marker_image = VALUES(marker_image),
                        video_url    = VALUES(video_url),
                        duration     = VALUES(duration),
                        category     = VALUES(category),
                        is_hot       = VALUES(is_hot),
                        update_time  = NOW(6);;
